export {
  buildSpineContentOffsets,
  buildSpinePageOffsets,
  estimateSpinePageCounts,
  getEffectiveSpineContentLength,
  getEffectiveSpinePageCount,
  mapDisplayPageToSpineLocation,
  mapProgressFractionToDisplayPage,
  mapProgressFractionToSpineLocation,
  mapSpineLocationToProgressFraction,
  mapSpineLocationToDisplayPage,
  normalizeDisplayPageForReadingStyle,
  normalizeStoredSpinePageCounts,
  type TextBookProgressLocation,
  type TextBookSpineLocation,
} from "@/utils/textBookPagination"
