#!/usr/bin/env bun
/**
 * Bundles pdfjs-dist into IIFE format for use inside a React Native WebView
 * without CDN or ES-module support.
 *
 * Run: bun run scripts/bundle-pdfjs.ts
 *
 * Output: app/library/PDF/pdfjsBundle.ts
 */
import * as fs from "fs"
import * as path from "path"
import * as os from "os"

const PDFJS_VERSION = JSON.parse(
  fs.readFileSync("node_modules/pdfjs-dist/package.json", "utf8"),
).version

const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "pdfjs-bundle-"))

const pdfEntry = path.join(tmpDir, "pdf_entry.mjs")
const workerEntry = path.join(tmpDir, "pdf_worker_entry.mjs")
const pdfOut = path.join(tmpDir, "pdf.bundle.js")
const workerOut = path.join(tmpDir, "pdf.worker.bundle.js")

const pdfSrc = path.resolve("node_modules/pdfjs-dist/build/pdf.min.mjs")
const workerSrc = path.resolve("node_modules/pdfjs-dist/build/pdf.worker.min.mjs")

fs.writeFileSync(
  pdfEntry,
  `import * as lib from ${JSON.stringify(pdfSrc)}; globalThis.pdfjsLib = lib;`,
)
fs.writeFileSync(
  workerEntry,
  `import { WorkerMessageHandler } from ${JSON.stringify(workerSrc)}; globalThis.WorkerMessageHandler = WorkerMessageHandler;`,
)

const { spawnSync } = await import("child_process")

let result = spawnSync("bun", ["build", "--bundle", "--format=iife", pdfEntry, "--outfile", pdfOut])
if (result.status !== 0) {
  console.error("Failed to bundle pdf.min.mjs:", result.stderr?.toString())
  process.exit(1)
}

result = spawnSync("bun", [
  "build",
  "--bundle",
  "--format=iife",
  workerEntry,
  "--outfile",
  workerOut,
])
if (result.status !== 0) {
  console.error("Failed to bundle pdf.worker.min.mjs:", result.stderr?.toString())
  process.exit(1)
}

const pdfBundle = fs
  .readFileSync(pdfOut, "utf8")
  // `import.meta` is invalid in classic `<script>` execution inside WebView.
  // This code path is only used for Node canvas creation, so replacing it is safe.
  .replaceAll("import.meta.url", '""')
const workerBundle = fs.readFileSync(workerOut, "utf8")

const output = [
  "// Auto-generated by scripts/bundle-pdfjs.ts — do not edit manually.",
  `// pdfjs-dist@${PDFJS_VERSION}, IIFE bundles for use in WebView without CDN.`,
  "",
  "export const PDF_IIFE_BUNDLE: string = " + JSON.stringify(pdfBundle) + ";",
  "",
  "export const WORKER_IIFE_BUNDLE: string = " + JSON.stringify(workerBundle) + ";",
  "",
].join("\n")

const outFile = "app/library/PDF/pdfjsBundle.ts"
fs.writeFileSync(outFile, output)
fs.rmSync(tmpDir, { recursive: true })

console.log(`Generated ${outFile} (${Math.round(output.length / 1024)} KB) for pdfjs@${PDFJS_VERSION}`)
