/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
  addArgsEnhancer,
  clearDecorators,
} from "@storybook/react-native"

global.STORIES = [
  {
    titlePrefix: "",
    directory: "./.storybook/stories",
    files: "**/*.stories.?(ts|tsx|js|jsx)",
    importPathMatcher:
      "^\\.[\\\\/](?:\\.storybook\\/stories(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)\\/|\\/|$)(?!\\.)(?=.)[^/]*?\\.stories\\.(?:ts|tsx|js|jsx)?)$",
  },
]

import "@storybook/addon-ondevice-controls/register"
import "@storybook/addon-ondevice-actions/register"

import { argsEnhancers } from "@storybook/addon-actions/dist/modern/preset/addArgs"

import { decorators, parameters } from "./preview"

if (decorators) {
  if (__DEV__) {
    // stops the warning from showing on every HMR
    require("react-native").LogBox.ignoreLogs([
      "`clearDecorators` is deprecated and will be removed in Storybook 7.0",
    ])
  }
  // workaround for global decorators getting infinitely applied on HMR, see https://github.com/storybookjs/react-native/issues/185
  clearDecorators()
  decorators.forEach((decorator) => addDecorator(decorator))
}

if (parameters) {
  addParameters(parameters)
}

try {
  argsEnhancers.forEach((enhancer) => addArgsEnhancer(enhancer))
} catch {}

const getStories = () => {
  return {
    "./.storybook/stories/Button.stories.tsx": require("../stories/Button.stories"),
    "./.storybook/stories/BookDescriptionItem.stories.tsx": require("../stories/BookDescriptionItem.stories"),
    "./.storybook/stories/BookImageItem.stories.tsx": require("../stories/BookImageItem.stories"),
    "./.storybook/stories/Checkbox.stories.tsx": require("../stories/Checkbox.stories"),
    "./.storybook/stories/Heading.stories.tsx": require("../stories/Heading.stories"),
    "./.storybook/stories/screens/ConnectScreen.stories.tsx": require("../stories/screens/ConnectScreen.stories"),
    "./.storybook/stories/screens/CalibreRootScreen.stories.tsx": require("../stories/screens/CalibreRootScreen.stories"),
  }
}

configure(getStories, module, false)
